name: hls4ml-tutorial
channels:
    - conda-forge
dependencies:
    - python=3.6
    - pip==21.3.1
    - pip:
        - scikit-learn==0.24.2
        - hls4ml==0.6.0
        - tensorflow==2.4.2
        - pandas==1.1.5
        - matplotlib==3.3.4
